### ISSUE TITLE
Add histogram

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-funnel-vis#1]
- add a histogram to the bottom of each stage, sitting under the existing circles
- this will display the number of leads per day prior to the current date.
- date range to be arguments (not necessarily max/min of provided values)
- each item in the histogram will be a stacked bar, colour coded to match the sources. For example - http://bl.ocks.org/sbrudz/8ac4f4102f787d0fcea5

![funnel-histo](https://cloud.githubusercontent.com/assets/826458/12500687/56836526-c11a-11e5-8877-755ac0c10639.png)

**Comment by goddice** [comment]
This is the result view of the histogram
The code is here: https://github.com/goddice/kademi-funnel-vis
You can try it.

![image](https://cloud.githubusercontent.com/assets/4031893/12543956/9bdb2276-c2fa-11e5-8f36-1c5271a87cd7.png)

**Comment by bradmac** [comment]
Looks good! This will normally be used with date ranges of between 1 and 12 months, ie 30 to 365 days. Does the layout work with that?

**Comment by bradmac** [comment]
But looks as though you havent actually pushed yet. There's not commits other then mine

**Comment by bradmac** [comment]
I've added more data points to the json, and you can see they run into each other
![histo-dates](https://cloud.githubusercontent.com/assets/826458/12547522/e326130a-c3b5-11e5-83bf-0f4c59744696.png)

What we need is sensible display of dates, like what nvd3 does:
http://nvd3.org/examples/linePlusBar.html

**Comment by bradmac** [comment]
Also, can you please limit the histogram height to no more then 25% of the height of the stage

**Comment by goddice** [comment]
I have fixed these two issues. Now the date display will automatically arranged by the width of the chart.

![image](https://cloud.githubusercontent.com/assets/4031893/12557244/5fa5524a-c34f-11e5-86e3-7b975d71a624.png)

**Comment by bradmac** [comment]
Looks great :)

Reduced the font size for dates and added data points.
