### ISSUE TITLE
Onclick event for bubbles and legend labels

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-funnel-vis#11]
To allow the visualisation to be interactive, we want the user to be able to click on circles or labels in the legend to filter on matching data.

To implement this please add a callback handler to the jquery config options, which is invoked when they are clicked.

To allow this to be used for filtering, we need to be able to associate an ID with the display text

```
$(".viz").funnel({
  onclick : function(id, text) {
     console.log("you clicked id=" + id + " and text " + text";
  }
});
```

Source items will have an extra property called id. This should be used as the unique identifier for sources. Eg:

```
                {
                    "name": "organic",
                    "id" : "124",
                    "count": 10,
                    "bydate": [
                        {
                            "data": "1/1/2016",
                            "leads": 5
                        }
                    ]
                },
```

**Comment by bradmac** [comment]
@goddice please let me know if you're happy to proceed. This is quite urgent.

**Comment by goddice** [comment]
What do you want to filter? How to use the "id"?

**Comment by bradmac** [comment]
No, you dont need to do any filtering. You just need to give us the ID back in the inclck handler

**Comment by goddice** [comment]
Only the first stage has id? So in fact, the id is just the id for the source name? e.g, google is 123 and facebook is 125 etc. ?

**Comment by goddice** [comment]
OK, now click the circle or the legend circle will output the id in the console.

**Comment by bradmac** [comment]
Awesome
