### ISSUE TITLE
Update funnel styles

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-funnel-vis#14]
Please update the funnel layout according to this image. Just the funnel and legend, not the page heading etc

![funnel](https://cloud.githubusercontent.com/assets/826458/12642088/7f360048-c618-11e5-9f6d-076cd3c00784.png)

**Comment by goddice** [comment]
Do you need the stage name?

![image](https://cloud.githubusercontent.com/assets/4031893/12652094/f271f84c-c5ae-11e5-9a83-95632ef888e1.png)

**Comment by goddice** [comment]
fixed

**Comment by bradmac** [comment]
- yes, we need the stage name
- add a gradient as per the attached image
- put the legend in a box with shadow

**Comment by goddice** [comment]
All done.

![image](https://cloud.githubusercontent.com/assets/4031893/12662527/9d5db3b8-c5e6-11e5-87f7-159d82589420.png)

**Comment by goddice** [comment]
User can set the stage font color(default is pink) and the small bounding box's color(default is black) in the jQuery option.

**Comment by bradmac** [comment]
Just one more thing here, there's not enough padding inside the stage label, so can you make that a config option?

**Comment by goddice** [comment]
What do you mean by padding? The color?

**Comment by bradmac** [comment]
padding in the space between a box and the content inside it

http://www.geekchamp.com/css-tutorials/11-css3-margin-and-padding

**Comment by goddice** [comment]
All done.

**Comment by bradmac** [comment]
Perfect, thanks
