### ISSUE TITLE
Repackage as a jquery plugin

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-funnel-vis#2]
With arguments provided as config options

For example

``` javascript
$("div.funnel").funnel({
stageHeight: 200px,
startDate: "1/1/2015",
endDate: "1/2/2015"
});
```

**Comment by goddice** [comment]
Do we need startDate and endDate?

**Comment by bradmac** [comment]
Actually no, not at the moment

**Comment by bradmac** [comment]
But would be like to apply various styles to the funnel. Such as
- font (family, size, style) for stage names (ie on the left)
- font for legend names (ie on the right)
- font for histogram labels
- background colour of the funnel
- border colour and thickness of the funnel

**Comment by goddice** [comment]
OK, I have wrapped it up as a jQuery plugin. I will add these parameters.

**Comment by goddice** [comment]
Should finish it very soon.

**Comment by goddice** [comment]
Have finished the repackage.

**Comment by bradmac** [comment]
Perfect!
