### ISSUE TITLE
Increase padding for the sources legend

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-funnel-vis#3]
As you can see below the funnel sits on top of the sources legend. Need some more space between them
![funnel-histo](https://cloud.githubusercontent.com/assets/826458/12500792/37dce6e6-c11b-11e5-8063-5bca3c54b9e3.png)

**Comment by goddice** [comment]
OK, that is fine

**Comment by goddice** [comment]
I think this is already OK now?

**Comment by goddice** [comment]
I have adjust the space.

**Comment by bradmac** [comment]
Yep, looks better
