### ISSUE TITLE
Hover tool tips

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-funnel-vis#6]
Could you please advise on the viability of
- adding tooltips displayed on hover over circles, which state the source and number of leads
- adding tooltips for the data points in the histogram, showing the date and the number of leads for each source at that date

**Comment by goddice** [comment]
Tooltip on chart is OK.
I am still working on tooltip on circle. It is not easy because they are dynamics.

**Comment by bradmac** [comment]
:+1:

**Comment by goddice** [comment]
The tooltip task is done.

**Comment by bradmac** [comment]
Awesome
